### ISSUE TITLE
PROJ: Write Your Bio

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/open#10]
## MENTOR
@decause-gov

## BRIEF DESCRIPTION
Create a Bio for your README.md file

## SCOPING
- Hours

## REQUIRED DELIVERABLES
See below

## DESIRED DATE WINDOW (June, July, August, Any)
- June

## NOTES/INSPO
Create a Bio with the following elements:

- Name
- Preferred Name/Nickname
- preferred pronouns
- TimeZone / Core Hours
- Goals for Internship
- Goals for After Internship
- Hobbies/Interests
- Funfact(s) 
- Fav Emoji

This bio will be used to introduce yourself to members of the team and schedule ‘coffee chats’ with DSAC members.

**Comment by Gaelan** [comment]
I assume you just want it here?

* **Name:** Gaelan Steele
* **Preferred Name/Nickname:** as above
* **preferred pronouns:** she/her or they/them
* **TimeZone / Core Hours:** Pacific Time. I typically work [9am-5:30pm Pacific](https://www.worldtimebuddy.com/?qm=1&lid=5809844,5574991,4887398,5128581&h=5809844&date=2023-6-16&sln=9-18.5&hf=1) - I might start and finish a little earlier some days if there's an early meeting or I wake up earlier.
* **Goals for Internship:** Do work that makes someone's life easier, whether that's a patient, a healthcare provider, or someone at DSAC/CMS. Career-wise, get a sense of whether civic tech (and especially the federal government) is a field I'd be interested in long term.
* **Goals for After Internship:** Finish my last year at college. After that is something of an open question - trying to find work in the tech industry that's both intellectually interesting and does good, which it turns out is rather tricky.
* **Hobbies/Interests:** Big nerd about public transport. Will derail any conversation into a conversation about linguistics.
* **Funfact(s):** Used to speak fluent Mandarin, though it's quite rusty these days.
* **Fav Emoji:** 🦀

**Comment by shwetakumarr** [comment]
**- Name: **Shweta Kumar**
- Preferred Name/Nickname: **Shweta Kumar**
- preferred pronouns: **She/her**
- TimeZone / Core Hours: **Eastern, 9am - 5:30pm EST**
- Goals for Internship: **Strengthen my skills in fields of interest such as web dev and ML. Make a direct, positive impact on people's lives. Explore being a civic technologist!**
- Goals for After Internship: **Continue my education at school. Hopefully start to identify where I see my career taking me.**
- Hobbies/Interests: **Working out, Crocheting/Knitting, Puzzles!**
- Funfact(s): **I've visited over half the states in the US.**
- Fav Emoji: 🫶🏽**

**Comment by navila-luna** [comment]
* Name: Nicole Avila
* Preferred Name: Nicole
* Pronouns: she/her/hers
* TimeZone/ Core Hours: Eastern, 8am - 4:30pm
* Goals for Internship: Gain experience doing backend and front-end work in a corporate environment while also making a meaningful impact to my community. I also look forward to learning more about healthcare policies!
* Hobbies/Interest: Working out, listening to music, making music, & making projects related to music or wellness.  I am also very much interested in talking about pop culture music, health, and the ethics of data privacy.
* Funfact: I'm can mimic certain bird calls.
* Fav Emoji:  😂
